# Generated by Django 3.2.8 on 2021-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ticker', models.CharField(max_length=4)),
                ('sign', models.CharField(max_length=1)),
            ],
        ),
    ]
