# Generated by Django 3.2.8 on 2021-10-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency'),
        ),
    ]
